# Generated by Django 4.1.3 on 2022-12-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('Location', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=250)),
                ('Amount', models.CharField(max_length=50)),
                ('Hours', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='scholarship/images')),
            ],
        ),
    ]
