# Generated by Django 4.1.3 on 2022-12-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactadmin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactadmin',
            name='name',
        ),
    ]
