# Generated by Django 4.1.3 on 2022-11-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('app', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.DeleteModel('todo'),
        migrations.RunSQL(sql='''
          DELETE FROM django_admin_log
          WHERE content_type_id = 7;
        ''')
    ]
