# Generated by Django 4.1.4 on 2022-12-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_smmarydatabank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='SmmaryDataBank',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
