# Generated by Django 4.1.3 on 2022-12-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsForm',
        ),
    ]
