# Generated by Django 4.1.4 on 2022-12-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_smmarydatabank_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='SmmaryDataBank',
            name='file',
            field=models.FileField(upload_to='file/', verbose_name='summary files'),
        ),
    ]
