# Generated by Django 4.1.3 on 2023-01-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_user'),
        ('app', '0006_alter_smmarydatabank_file'),
    ]

    operations = [
    ]
