# Generated by Django 4.1.3 on 2022-12-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_smmarydatabank_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reason', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('scholarship', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
