# Generated by Django 4.1.4 on 2023-01-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_0004_delete_user_0006_alter_smmarydatabank_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('Location', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=250)),
                ('Amount', models.CharField(max_length=50)),
                ('Hours', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='scholarship/images')),
            ],
        ),
    ]
