# Generated by Django 4.1.5 on 2023-01-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='image',
        ),
    ]
