# Generated by Django 4.1.3 on 2023-01-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_donationsmodel'),
        ('app', '0008_scholarship'),
    ]

    operations = [
    ]
