# Generated by Django 4.1.4 on 2023-01-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_0007_donationsmodel_0008_scholarship'),
        ('app', '0009_remove_scholarship_image'),
    ]

    operations = [
    ]
