# Generated by Django 4.1.3 on 2023-01-07 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_donationsmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactadmin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactadmin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
