# Generated by Django 4.1.4 on 2023-01-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20230110_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationsmodel',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
