# Generated by Django 4.1.3 on 2023-01-07 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contactadmin_created_at_contactadmin_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
