# Generated by Django 4.1.5 on 2023-01-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_scholarship_image'),
        ('app', '0012_contactusmodel_created_at_contactusmodel_updated_at'),
    ]

    operations = [
    ]
