# Generated by Django 4.1.3 on 2023-01-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_donationsmodel_amount'),
        ('app', '0012_contactusmodel_created_at_contactusmodel_updated_at'),
    ]

    operations = [
    ]
