# Generated by Django 4.1.3 on 2023-01-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20230109_2035'),
        ('app', '0013_merge_20230112_0858'),
        ('app', '0013_merge_20230113_2130'),
    ]

    operations = [
    ]
