# Generated by Django 4.1.5 on 2023-01-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_donationsmodel_amount'),
        ('app', '0013_merge_20230109_2035'),
    ]

    operations = [
    ]
