# Generated by Django 4.1.5 on 2023-01-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20230113_2130'),
        ('app', '0014_merge_20230113_1915'),
    ]

    operations = [
    ]
