# Generated by Django 4.1.3 on 2023-01-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20230114_1126'),
        ('app', '0015_merge_20230114_1504'),
    ]

    operations = [
    ]
