# Generated by Django 4.1.3 on 2023-01-15 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20230114_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsmodel',
            name='cardCode',
            field=models.CharField(default=0, max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_verification_code', message='Please enter a valid verification code (3/4 digits).', regex='^([0-9]{3,4})$')]),
        ),
        migrations.AddField(
            model_name='donationsmodel',
            name='cardNumber',
            field=models.CharField(default=0, max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_credit_card', message='Please enter a valid credit card number.', regex='^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\\\d{3})\\d{11})$')]),
        ),
        migrations.AddField(
            model_name='donationsmodel',
            name='expiryDate',
            field=models.CharField(default='MM-YY', max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_expiry_date', message='Please enter a valid expiry date (MM-YY - M = month, Y = year).', regex='^\\d{2}-\\d{2}$')]),
        ),
        migrations.AddField(
            model_name='donationsmodel',
            name='nameOnCard',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='requirements',
            field=models.CharField(max_length=500),
        ),
    ]
