# Generated by Django 4.1.3 on 2022-12-24 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/avatars/'),
        ),
    ]
