# Generated by Django 4.1.3 on 2022-12-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
