# Generated by Django 4.1.3 on 2022-12-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_user_avatar_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
