# Generated by Django 4.1.3 on 2022-12-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_bio_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_avatar',
            field=models.ImageField(default='user_profile/avatars/default.jpg', upload_to='user_profile/avatars/'),
        ),
    ]
