# Generated by Django 4.1.5 on 2023-01-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_scholarship_image'),
        ('accounts', '0009_alter_customuser_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Scholarship',
            field=models.ManyToManyField(blank=True, to='app.scholarship'),
        ),
    ]
