# Generated by Django 4.1.5 on 2023-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.CharField(choices=[('HEBR', 'Hebrew University of Jerusalem'), ('TAU', 'Tel Aviv University'), ('TECH', 'Technion - Israel Institute of Technology'), ('BGU', 'Ben-Gurion University of the Negev'), ('WEIZ', 'Weizmann Institute of Science'), ('BIU', 'Bar-Ilan University'), ('HAIFA', 'University of Haifa'), ('ARIEL', 'Ariel University'), ('OPEN', 'Open University of Israel'), ('ONO', 'Ono Academic College'), ('IDC', 'Interdisciplinary Center Herzliya'), ('BEZ', 'Bezalel Academy of Arts and Design'), ('HUJI', 'The Hebrew University of Jerusalem'), ('SCE', 'Shamoon College of Engineering')], max_length=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
